all_champion_id = {
    1: "Annie",
    2: "Olaf",
    3: "Galio",
    4: "TwistedFate",
    5: "XinZhao",
    6: "Urgot",
    7: "LeBlanc",
    8: "Vladimir",
    9: "Fiddlesticks",
    10: "Kayle",
    11: "Master Yi",
    12: "Alistar",
    13: "Ryze",
    14: "Sion",
    15: "Sivir",
    16: "Soraka",
    17: "Teemo",
    18: "Tristana",
    19: "Warwick",
    20: "Nunu",
    21: "MissFortune",
    22: "Ashe",
    23: "Tryndamere",
    24: "Jax",
    25: "Morgana",
    26: "Zilean",
    27: "Singed",
    28: "Evelynn",
    29: "Twitch",
    30: "Karthus",
    31: "ChoGath",
    32: "Amumu",
    33: "Rammus",
    34: "Anivia",
    35: "Shaco",
    36: "Dr.Mundo",
    37: "Sona",
    38: "Kassadin",
    39: "Irelia",
    40: "Janna",
    41: "Gangplank",
    42: "Corki",
    43: "Karma",
    44: "Taric",
    45: "Veigar",
    48: "Trundle",
    50: "Swain",
    51: "Caitlyn",
    53: "Blitzcrank",
    54: "Malphite",
    55: "Katarina",
    56: "Nocturne",
    57: "Maokai",
    58: "Renekton",
    59: "JarvanIV",
    60: "Elise",
    61: "Orianna",
    62: "Wukong",
    63: "Brand",
    64: "LeeSin",
    67: "Vayne",
    68: "Rumble",
    69: "Cassiopeia",
    72: "Skarner",
    74: "Heimerdinger",
    75: "Nasus",
    76: "Nidalee",
    77: "Udyr",
    78: "Poppy",
    79: "Gragas",
    80: "Pantheon",
    81: "Ezreal",
    82: "Mordekaiser",
    83: "Yorick",
    84: "Akali",
    85: "Kennen",
    86: "Garen",
    89: "Leona",
    90: "Malzahar",
    91: "Talon",
    92: "Riven",
    96: "KogMaw",
    98: "Shen",
    99: "Lux",
    101: "Xerath",
    102: "Shyvana",
    103: "Ahri",
    104: "Graves",
    105: "Fizz",
    106: "Volibear",
    107: "Rengar",
    110: "Varus",
    111: "Nautilus",
    112: "Viktor",
    113: "Sejuani",
    114: "Fiora",
    115: "Ziggs",
    117: "Lulu",
    119: "Draven",
    120: "Hecarim",
    121: "KhaZix",
    122: "Darius",
    126: "Jayce",
    127: "Lissandra",
    131: "Diana",
    133: "Quinn",
    134: "Syndra",
    136: "AurelionSol",
    141: "Kayn",
    142: "Zoe",
    143: "Zyra",
    145: "Kaisa",
    150: "Gnar",
    154: "Zac",
    157: "Yasuo",
    161: "VelKoz",
    163: "Taliyah",
    164: "Camille",
    201: "Braum",
    202: "Jhin",
    203: "Kindred",
    222: "Jinx",
    223: "TahmKench",
    235: "Senna",
    236: "Lucian",
    238: "Zed",
    240: "Kled",
    245: "Ekko",
    246: "Qiyana",
    254: "Vi",
    266: "Aatrox",
    267: "Nami",
    268: "Azir",
    350: "Yuumi",
    412: "Thresh",
    420: "Illaoi",
    421: "RekSai",
    427: "Ivern",
    429: "Kalista",
    432: "Bard",
    497: "Rakan",
    498: "Xayah",
    516: "Ornn",
    517: "Sylas",
    523: "Aphelios",
    518: "Neeko",
    555: "Pyke",
    875: "Sett",
    876: "Lillia",
}
"""
p10_5_wr = {
    "Annie": 52.41,
    "Olaf": 51.80,
    "Galio": 48.85,
    "TwistedFate": 50.04,
    "XinZhao": 50.93,
    "Urgot": 46.31,
    "LeBlanc": 48.63,
    "Vladimir": 50.49,
    "Fiddlesticks": 48.33,
    "Kayle": 51.24,
    "Master Yi": 50.36,
    "Alistar": 51.18,
    "Ryze": 46.48,
    "Sion": 52.18,
    "Sivir": 50.53,
    "Soraka": 49.57,
    "Teemo": 50.9,
    "Tristana": 49.55,
    "Warwick": 52.03,
    "Nunu": 54.22,
    "MissFortune": 52.04,
    "Ashe": 50.49,
    "Tryndamere": 50,
    "Jax": 50.56,
    "Morgana": 47.80,
    "Zilean": 51.23,
    "Singed": 56.78,
    "Evelynn": ,
    "Twitch",
    "Karthus",
    "ChoGath",
    "Amumu",
    "Rammus",
    "Anivia",
    "Shaco",
    "Dr.Mundo",
    "Sona",
    "Kassadin",
    "Irelia",
    "Janna",
    "Gangplank",
    "Corki",
    "Karma",
    "Taric",
    "Veigar",
    "Trundle",
    "Swain",
    "Caitlyn",
    "Blitzcrank",
    "Malphite",
    "Katarina",
    "Nocturne",
    "Maokai",
    "Renekton",
    "JarvanIV",
    "Elise",
    "Orianna",
    "Wukong",
    "Brand",
    "LeeSin",
    "Vayne",
    "Rumble",
    "Cassiopeia",
    "Skarner",
    "Heimerdinger",
    "Nasus",
    "Nidalee",
    "Udyr",
    "Poppy",
    "Gragas",
    "Pantheon",
    "Ezreal",
    "Mordekaiser",
    "Yorick",
    "Akali",
    "Kennen",
    "Garen",
    "Leona",
    "Malzahar",
    "Talon",
    "Riven",
    "KogMaw",
    "Shen",
    "Lux",
    "Xerath",
    "Shyvana",
    "Ahri",
    "Graves",
    "Fizz",
    "Volibear",
    "Rengar",
    "Varus",
    "Nautilus",
    "Viktor",
    "Sejuani",
    "Fiora",
    "Ziggs",
    "Lulu",
    "Draven",
    "Hecarim",
    "KhaZix",
    "Darius",
    "Jayce",
    "Lissandra",
    "Diana",
    "Quinn",
    "Syndra",
    "AurelionSol",
    "Kayn",
    "Zoe",
    "Zyra",
    "Kaisa",
    "Gnar",
    "Zac",
    "Yasuo",
    "VelKoz",
    "Taliyah",
    "Camille",
    "Braum",
    "Jhin",
    "Kindred",
    "Jinx",
    "TahmKench",
    "Senna",
    "Lucian",
    "Zed",
    "Kled",
    "Ekko",
    "Qiyana",
    "Vi",
    "Aatrox",
    "Nami",
    "Azir",
    "Yuumi",
    "Thresh",
    "Illaoi",
    "RekSai",
    "Ivern",
    "Kalista",
    "Bard",
    "Rakan",
    "Xayah",
    "Ornn",
    "Sylas",
    "Aphelios",
    "Neeko",
    "Pyke",
    "Sett",
    "Lillia",
}
"""

class ChampionInfo(object):
    def __init__(self):
        self.ids = all_champion_id

    def get_champion_name(self, id):
        return self.ids[id]
